/**
 * Blackpink Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');
const { bold, italic, pick, SLANG, voice } = require('../../utils/format');

module.exports = {
  name: 'blackpink',
  reactions: { received: '🖤', generating: '🖌️', done: '💖' },
  aliases: [],
  category: 'textmaker',
  description: 'Create blackpink text effect',
  usage: '.blackpink <text>',
  
  async execute(sock, msg, args, extra) {
    const prefix = config.prefix || '.';
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: `_${voice.lead('neutral')}, give me text to work with_\n\n_Example:_ ${prefix}blackpink Nick` 
        }, { quoted: msg });
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `*GENERATED BY ${config.botName}*\n_${voice.lead('affirm')}, enjoy_`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in blackpink command:', error);
      extra.fail();
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ _${voice.openErr()} — ${error.message}_` 
      }, { quoted: msg });
    }
  }
};

