/**
 * Impressive Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');
const { bold, italic, pick, SLANG } = require('../../utils/format');

module.exports = {
  name: 'impressive',
  reactions: { received: '😲', generating: '🖌️', done: '👏' },
  aliases: [],
  category: 'textmaker',
  description: 'Create impressive text effect',
  usage: '.impressive <text>',
  
  async execute(sock, msg, args) {
    const prefix = config.prefix || '.';
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: `_${pick(SLANG.vibe)}, give me text to generate_\n\n_Example:_ ${prefix}impressive Nick`
        }, { quoted: msg });
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `*GENERATED BY ${config.botName}*\n_${pick(SLANG.vibe)}, enjoy_`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in impressive command:', error);
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ _${pick(SLANG.error)} — ${error.message}_` 
      }, { quoted: msg });
    }
  }
};

