/**
 * Purple Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');
const { bold, italic, pick, SLANG } = require('../../utils/format');

module.exports = {
  name: 'purple',
  aliases: [],
  category: 'textmaker',
  description: 'Create purple text effect',
  usage: '.purple <text>',
  
  async execute(sock, msg, args) {
    const prefix = config.prefix || '.';
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: `_${pick(SLANG.vibe)}, give me text to generate_\n\n_Example:_ ${prefix}purple Nick` 
        }, { quoted: msg });
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/purple-text-effect-online-100.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `*GENERATED BY ${config.botName}*\n_${pick(SLANG.vibe)}, enjoy_`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in purple command:', error);
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ _${pick(SLANG.error)} — ${error.message}_` 
      }, { quoted: msg });
    }
  }
};

