/**
 * Snow Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');
const { bold, italic, pick, SLANG, voice } = require('../../utils/format');

module.exports = {
  name: 'snow',
  reactions: { received: '⛄', generating: '🖌️', done: '❄️' },
  aliases: [],
  category: 'textmaker',
  description: 'Create snow text effect',
  usage: '.snow <text>',
  
  async execute(sock, msg, args, extra) {
    const prefix = config.prefix || '.';
    try {
      const text = args.join(' ');
      if (!text) {
        return await sock.sendMessage(msg.key.remoteJid, { 
          text: `_${voice.lead('neutral')}, give me text to generate_\n\n_Example:_ ${prefix}snow Nick` 
        }, { quoted: msg });
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(msg.key.remoteJid, {
        image: { url: result.image },
        caption: `*GENERATED BY ${config.botName}*\n_${voice.lead('affirm')}, enjoy_`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in snow command:', error);
      extra.fail();
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ _${voice.openErr()} — ${error.message}_` 
      }, { quoted: msg });
    }
  }
};

